/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.ClientePessoaFisica;
import model.dao.ClientePessoaFisicaDao;

/**
 *
 * @author giova
 */
public class TelaClientePessoaFisica extends javax.swing.JFrame {

    /**
     * Creates new form TelaClientePessoaFisica
     */
    public TelaClientePessoaFisica() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTClientePessoaFisica.getModel();
        jTClientePessoaFisica.setRowSorter(new TableRowSorter(modelo));
        this.setVisible(rootPaneCheckingEnabled);
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTClientePessoaFisica.getModel();
        modelo.setNumRows(0);
        ClientePessoaFisicaDao cpfdao = new ClientePessoaFisicaDao();
        
        
        cpfdao.read().stream().forEach((p) -> {    
            modelo.addRow(new Object[]{
                p.getId(),
                p.getCPF(),
                p.getNome(),
                p.getEndereco(),
                p.getTelefone(),
                p.getEmail()
                
                
            });
            
        });
                
    }
    
    public void searchJTableForCpf(String cpf){
        DefaultTableModel modelo = (DefaultTableModel) jTClientePessoaFisica.getModel();
        modelo.setNumRows(0);
        ClientePessoaFisicaDao cpfdao = new ClientePessoaFisicaDao();
        
        
        cpfdao.searchPf(cpf).stream().forEach((p) -> {    
            modelo.addRow(new Object[]{
                p.getId(),
                p.getCPF(),
                p.getNome(),
                p.getEndereco(),
                p.getTelefone(),
                p.getEmail()
                
                
            });
            
        });
                
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCPF = new javax.swing.JTextField();
        txtNOME = new javax.swing.JTextField();
        txtENDERECO = new javax.swing.JTextField();
        txtTELEFONE = new javax.swing.JTextField();
        txtEMAIL = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientePessoaFisica = new javax.swing.JTable();
        txtBUSCAPF = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPF");

        jLabel2.setText("NOME");

        jLabel3.setText("ENDERECO");

        jLabel4.setText("TELEFONE");

        jLabel5.setText("EMAIL");

        jLabel6.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CADASTRO DE PESSOA FISICA");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTClientePessoaFisica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "NOME", "ENDERECO", "TELEFONE", "EMAIL"
            }
        ));
        jTClientePessoaFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientePessoaFisicaMouseClicked(evt);
            }
        });
        jTClientePessoaFisica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClientePessoaFisicaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientePessoaFisica);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNOME)
                            .addComponent(txtENDERECO)
                            .addComponent(txtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(71, 71, 71)
                        .addComponent(txtBUSCAPF)))
                .addGap(41, 41, 41)
                .addComponent(jButton4)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(txtBUSCAPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClientePessoaFisica pf = new ClientePessoaFisica();
        ClientePessoaFisicaDao pfdao = new ClientePessoaFisicaDao();
        pf.setCPF(txtCPF.getText());
        pf.setNome(txtNOME.getText());
        pf.setEndereco(txtENDERECO.getText());
        pf.setTelefone(txtTELEFONE.getText());
        pf.setEmail(txtEMAIL.getText());
        pfdao.createPf(pf); 
        
        txtCPF.setText("");
        txtNOME.setText("");
        txtENDERECO.setText("");
        txtTELEFONE.setText("");
        txtEMAIL.setText("");
        
        
        readJTable();
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ClientePessoaFisica pf = new ClientePessoaFisica();
        ClientePessoaFisicaDao pfdao = new ClientePessoaFisicaDao();
        pf.setCPF(txtCPF.getText());
        pf.setNome(txtNOME.getText());
        pf.setEndereco(txtENDERECO.getText());
        pf.setTelefone(txtTELEFONE.getText());
        pf.setEmail(txtEMAIL.getText());
        pf.setId((int)jTClientePessoaFisica.getValueAt(jTClientePessoaFisica.getSelectedRow(), 0));
        pfdao.updatePf(pf); 
        
        txtCPF.setText("");
        txtNOME.setText("");
        txtENDERECO.setText("");
        txtTELEFONE.setText("");
        txtEMAIL.setText("");
        
        
        readJTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTClientePessoaFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientePessoaFisicaMouseClicked
        if (jTClientePessoaFisica.getSelectedRow() != -1){
            
            txtCPF.setText(jTClientePessoaFisica.getValueAt(jTClientePessoaFisica.getSelectedRow(), 1).toString());
            txtNOME.setText(jTClientePessoaFisica.getValueAt(jTClientePessoaFisica.getSelectedRow(), 2).toString());
            txtENDERECO.setText(jTClientePessoaFisica.getValueAt(jTClientePessoaFisica.getSelectedRow(), 3).toString());
            txtTELEFONE.setText(jTClientePessoaFisica.getValueAt(jTClientePessoaFisica.getSelectedRow(), 4).toString());
            txtEMAIL.setText(jTClientePessoaFisica.getValueAt(jTClientePessoaFisica.getSelectedRow(), 5).toString());        
            
        }
    }//GEN-LAST:event_jTClientePessoaFisicaMouseClicked

    private void jTClientePessoaFisicaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClientePessoaFisicaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClientePessoaFisicaKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTClientePessoaFisica.getSelectedRow() != -1) {
            
        ClientePessoaFisica pf = new ClientePessoaFisica();
        ClientePessoaFisicaDao pfdao = new ClientePessoaFisicaDao();
        
        pf.setId((int)jTClientePessoaFisica.getValueAt(jTClientePessoaFisica.getSelectedRow(), 0));
        pfdao.deletePf(pf); 
        
        txtCPF.setText("");
        txtNOME.setText("");
        txtENDERECO.setText("");
        txtTELEFONE.setText("");
        txtEMAIL.setText("");
        
        
        readJTable();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        searchJTableForCpf(txtBUSCAPF.getText());
        
    }//GEN-LAST:event_jButton4ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientePessoaFisica;
    private javax.swing.JTextField txtBUSCAPF;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtENDERECO;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtTELEFONE;
    // End of variables declaration//GEN-END:variables
}
