/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.ClientePessoaJuridica;
import model.dao.ClientePessoaJuridicaDao;

/**
 *
 * @author giova
 */
public class TelaClientePessoaJuridica extends javax.swing.JFrame {

    /**
     * Creates new form TelaClientePessoaFisica
     */
    public TelaClientePessoaJuridica() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTClientePessoaJuridica.getModel();
        this.setVisible(rootPaneCheckingEnabled);
        
        readJTable();
    }
    
        public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTClientePessoaJuridica.getModel();
        modelo.setNumRows(0);
        ClientePessoaJuridicaDao cpjdao = new ClientePessoaJuridicaDao();
        
        
        cpjdao.readPj().stream().forEach((p) -> {    
            modelo.addRow(new Object[]{
                p.getId(),
                p.getCNPJ(),
                p.getIE(),
                p.getNome(),
                p.getEndereco(),
                p.getTelefone(),
                p.getEmail()
                
            });
            
        });
                
    }
        
        public void searchTableForCnpj(String cnpj){
        DefaultTableModel modelo = (DefaultTableModel) jTClientePessoaJuridica.getModel();
        modelo.setNumRows(0);
        ClientePessoaJuridicaDao cpjdao = new ClientePessoaJuridicaDao();
        
        
        cpjdao.searchPj(cnpj).stream().forEach((p) -> {    
            modelo.addRow(new Object[]{
                p.getId(),
                p.getCNPJ(),
                p.getIE(),
                p.getNome(),
                p.getEndereco(),
                p.getTelefone(),
                p.getEmail()
                
            });
            
        });
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCNPJ = new javax.swing.JTextField();
        txtNOME = new javax.swing.JTextField();
        txtENDERECO = new javax.swing.JTextField();
        txtTELEFONE = new javax.swing.JTextField();
        txtEMAIL = new javax.swing.JTextField();
        labelIE = new javax.swing.JLabel();
        txtIE = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientePessoaJuridica = new javax.swing.JTable();
        txtBUSCAPJ = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CNPJ");
        jLabel1.setToolTipText("");

        jLabel2.setText("NOME");

        jLabel3.setText("ENDERECO");

        jLabel4.setText("TELEFONE");

        jLabel5.setText("EMAIL");

        jLabel6.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CADASTRO DE PESSOA JURÍDICA");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });

        labelIE.setText("IE");

        txtIE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIEActionPerformed(evt);
            }
        });

        jTClientePessoaJuridica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CNPJ", "IE", "NOME", "ENDERECO", "TELEFONE", "EMAIL"
            }
        ));
        jTClientePessoaJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientePessoaJuridicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientePessoaJuridica);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNOME)
                                    .addComponent(txtENDERECO)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelIE)
                                            .addComponent(jLabel1))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIE, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtCNPJ)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addGap(72, 72, 72)
                                        .addComponent(txtBUSCAPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton4)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIE)
                    .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(txtBUSCAPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClientePessoaJuridica pj = new ClientePessoaJuridica();
        ClientePessoaJuridicaDao pjdao = new ClientePessoaJuridicaDao();
        pj.setCNPJ(txtCNPJ.getText());
        pj.setIE(txtIE.getText());
        pj.setNome(txtNOME.getText());
        pj.setEndereco(txtENDERECO.getText());
        pj.setTelefone(txtTELEFONE.getText());
        pj.setEmail(txtEMAIL.getText());
        pjdao.createPj(pj);
        
        txtCNPJ.setText("");
        txtIE.setText("");
        txtNOME.setText("");
        txtENDERECO.setText("");
        txtTELEFONE.setText("");
        txtEMAIL.setText("");
        
        
        readJTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIEActionPerformed

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void jTClientePessoaJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientePessoaJuridicaMouseClicked
        if (jTClientePessoaJuridica.getSelectedRow() != -1){
            
            txtCNPJ.setText(jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 1).toString());
            txtIE.setText(jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 2).toString());
            txtNOME.setText(jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 3).toString());
            txtENDERECO.setText(jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 4).toString());
            txtTELEFONE.setText(jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 5).toString());
            txtEMAIL.setText(jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 6).toString());
            
            
        }
    }//GEN-LAST:event_jTClientePessoaJuridicaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ClientePessoaJuridica pj = new ClientePessoaJuridica();
        ClientePessoaJuridicaDao pjdao = new ClientePessoaJuridicaDao();
        pj.setCNPJ(txtCNPJ.getText());
        pj.setIE(txtIE.getText());
        pj.setNome(txtNOME.getText());
        pj.setEndereco(txtENDERECO.getText());
        pj.setTelefone(txtTELEFONE.getText());
        pj.setEmail(txtEMAIL.getText());
        pj.setId((int)jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 0));
        pjdao.updatePj(pj);
        
        txtCNPJ.setText("");
        txtIE.setText("");
        txtNOME.setText("");
        txtENDERECO.setText("");
        txtTELEFONE.setText("");
        txtEMAIL.setText("");
        
        
        readJTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTClientePessoaJuridica.getSelectedRow() != -1){
            
        ClientePessoaJuridica pj = new ClientePessoaJuridica();
        ClientePessoaJuridicaDao pjdao = new ClientePessoaJuridicaDao();

        pj.setId((int)jTClientePessoaJuridica.getValueAt(jTClientePessoaJuridica.getSelectedRow(), 0));
        pjdao.deletePj(pj);
        
        txtCNPJ.setText("");
        txtIE.setText("");
        txtNOME.setText("");
        txtENDERECO.setText("");
        txtTELEFONE.setText("");
        txtEMAIL.setText("");
        
        
        readJTable();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        searchTableForCnpj(txtBUSCAPJ.getText());
        
    }//GEN-LAST:event_jButton4ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientePessoaJuridica;
    private javax.swing.JLabel labelIE;
    private javax.swing.JTextField txtBUSCAPJ;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtENDERECO;
    private javax.swing.JTextField txtIE;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtTELEFONE;
    // End of variables declaration//GEN-END:variables
}
